name: CI

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: build //...
    - name: test
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: test //...

  bench:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run benchmarks
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: run //:bench
